artifact_uri: file:///home/eduard/Desktop/projects/smart-grid-lab/mlflow/950858119059139203/998338edeb9c4ef7b8d653d77107dc2b/artifacts
end_time: 1789991094669
entry_point_name: ''
experiment_id: '950858119059139203'
lifecycle_stage: active
run_id: 998338edeb9c4ef7b8d653d77107dc2b
run_name: vaunted-mole-57
source_name: ''
source_type: 4
source_version: ''
start_time: 1789991094389
status: 3
tags: []
user_id: unknown
