artifact_uri: file:///home/eduard/Desktop/projects/smart-grid-lab/mlflow/914435013758270915/f59ba28e97ae4e3b8a39c5012a3cfce3/artifacts
end_time: 1790847778090
entry_point_name: ''
experiment_id: '914435013758270915'
lifecycle_stage: active
run_id: f59ba28e97ae4e3b8a39c5012a3cfce3
run_name: nimble-worm-301
source_name: ''
source_type: 4
source_version: ''
start_time: 1790847777775
status: 3
tags: []
user_id: unknown
